---
# Title: role-zabbix-4.0LTS
#
# Author: bitfinity-nl
# File: tasks/main.yml
#
# Description:
#   Playbook for deploying Zabbix 4.0LTS 
#   server/agent/proxy on Ubuntu 18.04LTS.
#

- name: "Zabbix server (Ubuntu)"
  import_tasks: server/zabbix-server.yml
  when:
    - ansible_distribution_version == "18.04"
    - ansible_architecture == "x86_64"
    - zbx_type == 'server'

- name: "Zabbix Agent (Ubuntu)"
  import_tasks: agent/ubuntu/zbx-agent-ubt1804.yml
  when:
    - ansible_distribution_version == "18.04"
    - ansible_architecture == "x86_64"
    - zbx_type == 'agent'

- name: "Zabbix Agent (Windows 64bit)"
  import_tasks: agent/windows/win-64bit-check.yml
  when:
    - ansible_os_family == "Windows"
    - ansible_architecture == "64-bit"
    - zbx_type == 'agent'