---
# Title: role-zabbix-4.0LTS
#
# Author: bitfinity-nl
# File: defaults/win-64bit-check.yml
#
# Description:
#   Playbook for deploying Zabbix 4.0LTS 
#   server/agent/proxy on Ubuntu 18.04LTS.

- name: "Check if package is already installed before downloading installation files. (64bit)"
  win_reg_stat:
    path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{{ zbx_win_agt_product_id }}'
  register: pkg_isinstalled

- name: "Print if app is installed"
  debug:
    msg: "{{ pkg_isinstalled }}"

- name: "import tasks/install"
  import_tasks: zbx-agent-win-amd64.yml
  when:
    - pkg_isinstalled.exists == false

- name: "Update config on Windows"
  import_tasks: zbx-agent-conf-update.yml
  when:
    - pkg_isinstalled.exists == true