---
# Title: role-zabbix-4.0LTS
#
# Author: bitfinity-nl
# File: defaults/zbx-agent-conf-update.yml
#
# Description:
#   Playbook for deploying Zabbix 4.0LTS 
#   server/agent/proxy on Ubuntu 18.04LTS.
#

- name: "Transfer zabbix_agentd.conf.j2 to c://program files//Zabbix Agent//"
  win_template:
    src: agent/zabbix_agentd.conf.j2
    dest: c:\\program files\\Zabbix Agent\\zabbix_agentd.conf
    backup: yes
  notify:
    - restart_win_zbx_agent