---
# Title: role-zabbix-4.0LTS
#
# Author: bitfinity-nl
# File: defaults/main.yml
#
# Description:
#   Playbook for deploying Zabbix 4.0LTS 
#   server/agent/proxy on Ubuntu 18.04LTS.
#
# Comment:
#   Override settings here, in your playbook or in your group_vars.  

- name: "Create local Ansible repository"
  win_file:
    path: "{{ zbx_pkg_local_repository }}"
    state: directory

- name: "Download Package"
  win_get_url:
    url: "{{ zbx_win_agt_url }}"
    dest: "{{ zbx_pkg_local_repository }}\\zabbix_agent-installer.msi"
    force: no

- name: "Installing {{ pkg_name }}"
  win_package:
    path: "{{ zbx_pkg_local_repository }}\\zabbix_agent-installer.msi"
    product_id: "{{ zbx_win_agt_product_id }}"
    arguments: "{{ zbx_win_agt_arguments }}"
    state: present

- name: "Removing installation files"
  win_file:
    path: "{{ zbx_pkg_local_repository }}"
    state: absent